### GENERAL SETTINGS ###

# Site settings
title: Club de Robótica FIUBA
description: "Porque estudiar puede ser divertido!"
baseurl: "" #important: start with /
url: "https://www.clubderobotica.com.ar"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

include:
  - _pages
