### GENERAL SETTINGS ###

# Site settings
title: Club de Robótica FIUBA
description: "Porque estudiar puede ser divertido!"
analytics: UA-31160782-1
baseurl: "" #important: start with /
url: "http://www.clubderobotica.com.ar"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  github:
    title: github
    url: https://github.com/cdrfiuba
  instagram:
    title: instagram
    url: https://www.instagram.com/cdrfiuba
  facebook:
    title: facebook
    url: https://www.facebook.com/cdrfiuba
  twitter:
    title: twitter
    url: https://www.twitter.com/cdrfiuba
  youtube:
    title: youtube
    url: https://www.youtube.com/cdrfiuba
  google-plus-square:
    title: google-plus-square
    url: https://plus.google.com/+cdrfiuba

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Av. Paseo Colón 850
    - Buenos Aires
    - Argentina.
email: clubderobotica@fi.uba.ar
site-email: info@clubderobotica.com.ar

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name:
    position:
    text:
    img: team01.jpg

# Short text about the club.
about:
  - Desde un ámbito académico-educativo para la integración de conocimientos en ingeniería, se abre El Club de Robótica como un espacio propuesto por Ingenieros y estudiantes para la investigación y el desarrollo de prototipos y actividades en robótica.
  - La filosofía del Club consiste en emplear los conocimientos adquiridos a lo largo de la carrera y combinarlos con la motivación y la participación activa de cada uno de sus integrantes. De ese modo se busca conjugar creatividad, dinamismo y acción que brindan como resultado proyectos reales en tiempos concretos."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Es lo más divertido que"
    author:
    position:
